trigger:
- main

pool:
  Hawkins-RevaTop

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/PilotPracticeUI/Dockerfile'
    buildContext: '**/PilotPracticeUI'