trigger:
- main

pool:
  Hawkins-RevaTop

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dir
  displayName: 'Repo content'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'hawkinsr/pilotpracticeui'
    command: 'buildAndPush'
    Dockerfile: './PilotPracticeUI/Dockerfile'
    buildContext: './PilotPracticeUI'
    tags: |
      $(Build.BuildId)
      latest

