trigger:
- main

pool:
  Hawkins-RevaTop

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
  


- script: ls -a
  displayName: 'Repo content'

- task: Docker@2
  inputs:
    containerRegistry: 'DockerHub'
    repository: 'pilotpracticeui'
    command: 'buildAndPush'
    Dockerfile: '**/PilotPracticeUI/Dockerfile'
    buildContext: '**/PilotPracticeUI'
    tags: |
      $(Build.BuildId)
      latest