name: UI build and deploy

on:
  push:
    branches:
      - main
    paths:
      - PilotPracticeUI/**
  pull_request:
    branches:
      - main
    paths:
      - PilotPracticeUI/**
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_38d4019349054f9880b129e99db025c6 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./PilotPracticeUI/
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}/pilotpracticeui:${{ github.sha }}, index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}/pilotpracticeui:latest
        file: ./PilotPracticeUI/Dockerfile

  deploy:
    runs-on: 'ubuntu-latest'
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PilotPractice'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_af2a2b095fec43e582000cb1fd64ac08 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}/pilotpracticeui:${{ github.sha }}'
