name: API build and deploy

on:
  push:
    branches:
      - main
    paths:
      - PilotPracticeApi/**
  pull_request:
    branches:
      - main
    paths:
      - PilotPracticeApi/**
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_fe39101a2e874a4782241b64b5d07afb }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a60a3a317768412b9ad96511948966b2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        context: ./PilotPracticeApi/
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}/pilotpracticeapi:${{ github.sha }}, index.docker.io/${{ secrets.AzureAppService_ContainerUsername_88fdfa0d887b409cbb1d17ac8ed0b539 }}/pilotpracticeapi:latest
        file: ./PilotPracticeAPI/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PilotPracticeAPI'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3b82b1e6d6654844a1317c914e7e8b16 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_fe39101a2e874a4782241b64b5d07afb }}/hawkinsr/pilotpracticeapi:${{ github.sha }}'
